### ISSUE TITLE
Snapcraft failed due to wrong base

### ISSUE THREAD

**Issue by andreolaya** [electron-userland/electron-installer-snap#24]
**Please describe your issue:**

Config, note already install @electron-forge/maker-snap.

```
"config": {
  "forge": {
    "packagerConfig": {},
    "makers": [
      {
        "name": "@electron-forge/maker-snap",
        "config": {
          "name": "testing"
        }
      },
      {
        "name": "@electron-forge/maker-deb",
        "config": {}
      }
    ]
  }
}
```

**Console output when you run electron-packager with the environment variable `DEBUG='electron-forge:*'`. Please include the stack trace if one exists.**

```
> electron-forge make

✔ Checking your system
✔ Resolving Forge Config
We need to package your application before we can make it
✔ Preparing to Package Application for arch: x64
✔ Preparing native dependencies
✔ Packaging Application
Making for the following targets: snap, deb
⠋ Making for target: snap - On platform: linux - For arch: x64The browser-sandbox feature will trigger a manual review in the Snap store.
⠇ Making for target: snap - On platform: linux - For arch: x64Cloning into '/tmp/electron-snap-118146s11f3JFNyOr/parts/desktop-gtk3/src'...
⠸ Making for target: snap - On platform: linux - For arch: x64remote: Enumerating objects: 33, done.        
remote: Counting objects: 100% (33/33), done.        
remote: Compressing objects: 100% (23/23), done.        h: x64remote: Compressing objects:  30% (7/23)           
remote: Total 1334 (delta 11), reused 23 (delta 9), pack-reused 1301        
Receiving objects: 100% (1334/1334), 241.65 KiB | 4.74 MiB/s, done.
Resolving deltas: 100% (690/690), done.
⠸ Making for target: snap - On platform: linux - For arch: x64Snapcraft failed (2)
Re-run with the environment variable DEBUG=electron-installer-snap:snapcraft for details.
✖ Making for target: snap - On platform: linux - For arch: x64

An unhandled error has occurred inside Forge:
An error occured while making for target: snap
Exited with status 2
Error: Exited with status 2
    at closeArgsToError (/home/andres/testing/node_modules/cross-spawn-promise/lib/index.js:12:17)
    at ChildProcess.closeArgsToError (/home/andres/testing/node_modules/cross-spawn-promise/lib/index.js:66:21)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

npm ERR! Linux 4.15.0-1030-gcp
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "make"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! testing@1.0.0 make: `electron-forge make`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testing@1.0.0 make script 'electron-forge make'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the testing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-forge make
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs testing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls testing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/andres/testing/npm-debug.log
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `snap()` function?**

```
npm run make

```

**Comment by malept** [comment]
There's not enough information here to help you out. Here's the error extracted from your output:

```
Snapcraft failed (2)
Re-run with the environment variable DEBUG=electron-installer-snap:snapcraft for details.
```
Can you please follow the instructions here to see why `snapcraft` is failing?

**Comment by andreolaya** [comment]
Please reproduce the following steps:

System Info: Linux testing 4.15.0-1030-gcp #32-Ubuntu SMP Wed Apr 10 10:27:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```
npm install -g @electron-forge/cli@beta
electron-forge init testing
```

Add the following config in package.json

```
"config": {
  "forge": {
    "packagerConfig": {},
    "makers": [
      {
        "name": "@electron-forge/maker-snap",
        "config": {
          "name": "testing"
        }
      }
    ]
  }
}
```

Now let's try to execute make with DEBUG=electron-installer-snap:snapcraft

```
npm run make
```

Console output

```
$ npm run make
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'make' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'premake', 'make', 'postmake' ]
5 info lifecycle testing@1.0.0~premake: testing@1.0.0
6 silly lifecycle testing@1.0.0~premake: no script for premake, continuing
7 info lifecycle testing@1.0.0~make: testing@1.0.0
8 verbose lifecycle testing@1.0.0~make: unsafe-perm in lifecycle true
9 verbose lifecycle testing@1.0.0~make: PATH: /usr/share/npm/bin/node-gyp-bin:/home/andres/testing/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle testing@1.0.0~make: CWD: /home/andres/testing
11 silly lifecycle testing@1.0.0~make: Args: [ '-c', 'electron-forge make' ]
12 silly lifecycle testing@1.0.0~make: Returned: code: 1  signal: null
13 info lifecycle testing@1.0.0~make: Failed to exec make script
14 verbose stack Error: testing@1.0.0 make: `electron-forge make`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid testing@1.0.0
16 verbose cwd /home/andres/testing
17 error Linux 4.15.0-1030-gcp
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "make"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error testing@1.0.0 make: `electron-forge make`
22 error Exit status 1
23 error Failed at the testing@1.0.0 make script 'electron-forge make'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the testing package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron-forge make
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs testing
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls testing
```

**Comment by malept** [comment]
That looks like the npm-debug.log output, not the console output.

**Comment by andreolaya** [comment]
> That looks like the npm-debug.log output, not the console output.

I'm sorry, I just updated.

**Comment by malept** [comment]
Run `export DEBUG=electron-installer-snap:snapcraft` and then `npm run make`.

**Comment by andreolaya** [comment]
> Run `export DEBUG=electron-installer-snap:snapcraft` and then `npm run make`.

Yes, please, check again

**Comment by malept** [comment]
What version of Ubuntu is this?

**Comment by andreolaya** [comment]
> What version of Ubuntu is this?

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Comment by malept** [comment]
In the config for maker-snap, set the snap config `'base': 'core18'` (corresponding to Ubuntu 18.04), which was added to Snapcraft in 3.0: https://snapcraft.io/blog/make-your-snap-development-faster
