### ISSUE TITLE
Native builds aren't supported on Raspbian GNU/Linux. You can however use 'snapcraft cleanbuild' with a container.

### ISSUE THREAD

**Issue by RebelSyntax** [electron-userland/electron-installer-snap#5]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-installer-snap/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
Question about the following DEBUG output:

Native builds aren't supported on Raspbian GNU/Linux. You can however use 'snapcraft cleanbuild' with a container.

I would like to create a snap of an Electron App that I have been successful packaging and distributing as a .deb.  So far, I have been packaging and making this successfully in the environment that the package is targeted at.  The app is a purpose built IoT app and will only ever be distributed on the same architecture as the build environment (armv7L).

I've successfully installed snapd and lxd on the build environment and I am able to create lxc with no problems.  

I got this error message in the debug output after running 'npm run make' which uses electron-forge make configured for 'snap' as the make target.  

I would like help or perhaps a little bit of guidance on what steps I would likely need to do next in order to get this snap created.  I've read lots of documentation on snapcraft and lxd.  I will likely be placing this build process into a CI/CD cloud solution, so it seems like I may need to go ahead and create an LXD on the build server from an armv7L architecture.  

From there, I am not sure where to go.  Is this something I can configure in Electron-Forge?  Will I still be able to initialize making with npm?  

Thanks in advance for any additional guidance, links, instructions or help you may offer.  

**Console output when you run electron-packager with the environment variable `DEBUG='electron-forge:*'`. Please include the stack trace if one exists.**

```
pi@raspberrypi:~/RebelSyntax/dev $ npm run make

> IoT-App@1.1.0 make /home/pi/RebelSyntax/dev
> DEBUG=electron-forge:* electron-forge make

WARNING: DEBUG environment variable detected.  Progress indicators will be sent over electron-forge:lifecycle
  electron-forge:lifecycle Process Started: Checking your system +0ms
  electron-forge:lifecycle Process Succeeded: Checking your system +1s
  electron-forge:runtime-config setting key: verbose to value: false +0ms
WARNING: DEBUG environment variable detected.  Progress indicators will be sent over electron-forge:lifecycle
  electron-forge:lifecycle Process Started: Resolving Forge Config +0ms
  electron-forge:project-resolver searching for project in: /home/pi/RebelSyntax/dev +0ms
  electron-forge:project-resolver electron-forge compatible package.json found in /home/pi/RebelSyntax/dev/package.json +32ms
  electron-forge:lifecycle Process Succeeded: Resolving Forge Config +58ms
  electron-forge:require-search searching [ '../makers/linux/snap.js',
  '../makers/generic/snap.js',
  'electron-forge-maker-snap',
  'snap',
  '/home/pi/RebelSyntax/dev/snap',
  '/home/pi/RebelSyntax/dev/node_modules/snap',
  '/home/pi/RebelSyntax/dev/node_modules/electron-forge/dist/makers/linux/snap.js',
  '/home/pi/RebelSyntax/dev/node_modules/electron-forge/dist/makers/generic/snap.js',
  '/home/pi/RebelSyntax/dev/node_modules/electron-forge/dist/api/electron-forge-maker-snap',
  '/home/pi/RebelSyntax/dev/node_modules/electron-forge/dist/api/snap',
  '/home/pi/RebelSyntax/dev/snap',
  '/home/pi/RebelSyntax/dev/node_modules/snap',
  '/home/pi/RebelSyntax/dev/node_modules/electron-forge/dist/api/makers/linux/snap.js',
  '/home/pi/RebelSyntax/dev/node_modules/electron-forge/dist/api/makers/generic/snap.js',
  '/home/pi/RebelSyntax/dev/node_modules/electron-forge/dist/api/node_modules/electron-forge-maker-snap',
  '/home/pi/RebelSyntax/dev/node_modules/electron-forge/dist/api/node_modules/snap',
  '/home/pi/RebelSyntax/dev/snap',
  '/home/pi/RebelSyntax/dev/node_modules/snap' ] relative to /home/pi/RebelSyntax/dev/node_modules/electron-forge/dist/api +0ms
  electron-forge:require-search testing ../makers/linux/snap.js +13ms
We need to package your application before we can make it
  electron-forge:lifecycle Process Started: Preparing to Package Application for arch: armv7l +59ms
  electron-forge:project-resolver searching for project in: /home/pi/RebelSyntax/dev +82ms
  electron-forge:project-resolver electron-forge compatible package.json found in /home/pi/RebelSyntax/dev/package.json +3ms
  electron-forge:hook could not find hook: generateAssets +0ms
  electron-forge:hook could not find hook: prePackage +1ms
  electron-forge:packager packaging with options { asar: true,
  overwrite: true,
  packageManager: 'npm',
  afterCopy: [ [Function] ],
  afterExtract: [ [Function] ],
  afterPrune: [ [Function] ],
  dir: '/home/pi/RebelSyntax/dev',
  arch: 'armv7l',
  platform: 'linux',
  out: '/home/pi/RebelSyntax/dev/out',
  electronVersion: '1.7.11',
  quiet: true } +0ms
  electron-forge:lifecycle Process Succeeded: Preparing to Package Application for arch: armv7l +2m
  electron-forge:lifecycle Process Started: Compiling Application +2ms
  electron-forge:lifecycle Process Succeeded: Compiling Application +7s
  electron-forge:lifecycle Process Started: Preparing native dependencies +56s
  electron-forge:lifecycle Process Succeeded: Preparing native dependencies +57s
  electron-forge:lifecycle Process Started: Packaging Application +1ms
  electron-forge:hook could not find hook: postPackage +5m
  electron-forge:lifecycle Process Succeeded: Packaging Application +47s
Making for the following targets:
  electron-forge:hook could not find hook: preMake +3ms
  electron-forge:lifecycle Process Started: Making for target: snap - On platform: linux - For arch: armv7l +5ms
Snapcraft failed (2)
Re-run with the environment variable DEBUG=electron-installer-snap:snapcraft for details.
  electron-forge:lifecycle Process Failed: Making for target: snap - On platform: linux - For arch: armv7l +9s

An unhandled error has occurred inside Forge:
An error occured while making for target: snap
Exited with status 2
Error: Exited with status 2
    at closeArgsToError (/home/pi/RebelSyntax/dev/node_modules/cross-spawn-promise/lib/index.js:20:16)
    at ChildProcess.<anonymous> (/home/pi/RebelSyntax/dev/node_modules/cross-spawn-promise/lib/index.js:76:19)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! IoT-App@1.1.0 make: `DEBUG=electron-forge:* electron-forge make`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the IoT-App@1.1.0 make script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-03-29T14_48_09_435Z-debug.log


pi@raspberrypi:~/RebelSyntax/dev $ npm run make

> IoT-App@1.1.0 make /home/pi/RebelSyntax/dev
> DEBUG=electron-installer-snap:* electron-forge make

✔ Checking your system
✔ Resolving Forge Config
We need to package your application before we can make it
✔ Preparing to Package Application for arch: armv7l
✔ Compiling Application
✔ Preparing native dependencies: 2 / 2
✔ Packaging Application
Making for the following targets:
⠙ Making for target: snap - On platform: linux - For arch: armv7l  electron-installer-snap:default_args Loading package.json defaults from /home/pi/RebelSyntax/dev/out/RebelSyntax-linux-armv7l/resources/app.asar +0ms
⠹ Making for target: snap - On platform: linux - For arch: armv7l  electron-installer-snap:yaml Loading YAML template /home/pi/RebelSyntax/dev/node_modules/electron-installer-snap/resources/snapcraft.yaml +0ms
  electron-installer-snap:yaml Writing new YAML file /tmp/electron-snap-63124pKJzFtyUAAj/snap/snapcraft.yaml +35ms
⠸ Making for target: snap - On platform: linux - For arch: armv7l  electron-installer-snap:snapcraft Running '/snap/bin/snapcraft snap --target-arch=armhf --output=/home/pi/RebelSyntax/dev/out/make/IoT-App_1.1.0_armhf.snap' in /tmp/electron-snap-63124pKJzFtyUAAj +0ms
⠼ Making for target: snap - On platform: linux - For arch: armv7lSetting target machine to 'armhf'
⠴ Making for target: snap - On platform: linux - For arch: armv7lNative builds aren't supported on Raspbian GNU/Linux. You can however use 'snapcraft cleanbuild' with a container.
⠇ Making for target: snap - On platform: linux - For arch: armv7lSnapcraft failed (2)
✖ Making for target: snap - On platform: linux - For arch: armv7l

An unhandled error has occurred inside Forge:
An error occured while making for target: snap
Exited with status 2
Error: Exited with status 2
    at closeArgsToError (/home/pi/RebelSyntax/dev/node_modules/cross-spawn-promise/lib/index.js:20:16)
    at ChildProcess.<anonymous> (/home/pi/RebelSyntax/dev/node_modules/cross-spawn-promise/lib/index.js:76:19)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! IoT-App@1.1.0 make: `DEBUG=electron-installer-snap:* electron-forge make`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the IoT-App@1.1.0 make script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-03-29T14_36_51_962Z-debug.log

```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `snap()` function?**

```
None
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

I will take the time to create a repro if it's really needed.  I think in this case, the formality will not be necessary since that is question and not a bug report.  Thanks!

**Comment by malept** [comment]
> Native builds aren't supported on Raspbian GNU/Linux. You can however use 'snapcraft cleanbuild' with a container.

This error comes from snapcraft itself, so native support is kind of out of my hands. However, from a non-Raspbian Linux installation (likely on an x86_64 arch), you _should_ be able to run:

```
electron-forge make --arch armv7l
```

Admittedly, I haven't tried running it.
